Login & UserDiagnoses html, css, disabled button if either usrname or…
mild-blue/tasks pull request #20
Opened 2022-08-17 10:39 UTC by nazuzunana

… password is empty, user object, storing user object in broswer localStorage, navigating to Home component.

First, I created a sign in form with a username input and a password input. Second, I created a CSS file and added styles for the sign in form. After that, I prepared the html code for the diagnose list of the user. After that, I disabled the sign in button if either username or password is empty, created a user object with patient information inside a logIn() function and stored the user object in the browser localStorage after submitting the sign in form. After that, I loaded the user object from the localStorage and displayed the user information in the UserDiagnoses component, which is displayed at the Home page.

I failed to navigate to Home page after submitting the sign in form, to set user to component state, and to display the name of the user in <h1> tag in the Home component.

2022-08-17 15:05 UTC, misslecter requested changes
Hezká práce! 

Za ten redirect se omlouvám, byla to moje chybka. Pushla jsem update a už by tě to mělo normálně po loginu přesměrovat. (Tip na logout: odstranit zaznam `user` v developer console prohlížeče v tabu `Application` -> `localStorage` -> `http://localhost:3000`)

Prosím tě o pár věcí:

1. Projdi si komentáře a zpracuj moje připomínky (normálně dál do tohoto pull requestu)
2. Mohla bys přidat `Home.scss` a nastylovat (jen nějak lehce) údaje o pacientovi? Jde mi o to, abys mrkla na koncepty SCSS: použití `&` a zanoření (viz Nesting https://sass-lang.com/guide). Používáme tyto principy teďka hodně často na projektech, tak at je projdeš předem.

Pak mě zase pingni mailem až to budeš mít hotové 😊 

Díky!

2022-08-17 15:05 UTC, misslecter commented on react-ts/src/pages/Login.css
> +  color: var(--link);
color definujes nejdriv na `var(--text)`, pak na `var(--link)`. Nech jedno z toho a vše co patří k `a` měj v tom jednom pravidlu

2022-08-17 15:05 UTC, misslecter commented on react-ts/src/pages/Login.css
> +  border-radius: 0%;
staci `border-radius: 0` bez procenta

2022-08-17 15:05 UTC, misslecter commented on react-ts/src/pages/Login.css
> +  font-size: medium;
dala bych konkretni ciselnou hodnotu. Buh vi jak ruzne prohlizece interpretuji `medium`

2022-08-17 15:05 UTC, misslecter commented on react-ts/src/pages/Login.tsx
> +    const patient1: User = {
tak `1` tam uplne nemusi byt ne? 😀 staci `const patient = ...`

2022-08-25 08:33 UTC, misslecter requested changes

2022-08-25 08:33 UTC, misslecter commented on react-ts/src/components/UserDiagnoses.tsx
> +  // });
vsak to tady skoro máš 😀 stačí jen vytahovat pacienta z localStorage vevnitr `useEffect`

```
const [patient, setPatient] = useState<User>();

useEffect(() => {
   const patientString = localStorage.getItem(userLocalStorageKey);
   setPatient(patientString ? JSON.parse(patientString) : undefined);
});
```

2022-08-25 08:33 UTC, misslecter commented on react-ts/src/pages/Home.css
> +}
tohle by slo zanorit do `.box`

2022-08-25 08:33 UTC, misslecter commented on react-ts/src/pages/Home.scss
> +  .box__info {
slo by pouzit `&__info`

2022-08-25 08:33 UTC, misslecter commented on react-ts/src/pages/Login.scss
> +.login-container {
mas toho vic s prefixem `login-`, ja bych to zanorila do jednoho tagu 

```
.login {
  &-container {
    ...
  }
  
  &-form {
    ...
  }

  &-link {
    ...
  }
}
```

2022-08-25 08:33 UTC, misslecter commented on react-ts/src/components/UserDiagnoses.tsx
> +          <p className="box__info">{patient.diagnoses[1]}</p>
pouzij `patient.diagnoses.map()` https://reactjs.org/docs/lists-and-keys.html#embedding-map-in-jsx

2022-08-25 08:33 UTC, misslecter commented on react-ts/src/pages/Home.tsx
> +      <p className="user__name">Todo: Display name of the user here</p>
Bylo by totiz hezke, kdybys pacienta vytahla z localStorage uz tady pomoci:

```
const [patient, setPatient] = useState<User>();

useEffect(() => {
   const patientString = localStorage.getItem(userLocalStorageKey);
   setPatient(patientString ? JSON.parse(patientString) : undefined);
});
```

a do `<UserDiagnoses />` poslala jen ty diagnozy, ktere by se tam jen hloupe v `.map()` vypsali:

```
<UserDiagnoses diagnoses={patient.diagnoses} />
```

Coz znamena tedy upravy:
1. Vytahnout pacienta z LS v `Home` komponente a ulozit si ho do state
2. Osetrit pripad, kdy pacient neni ulozeny (jak se to deje ted v `UserDiagnoses`) uz v `Home` komponente
3. Definovat Props komponenty `UserDiagnoses`, ktere by obsahovali jen diagnozy
4. Poslat `patient.diagnoses` do `UserDiagnoses`
5. V `UserDiagnoses` vypisovat jen ty diagnozy (jak napovida nazev komponenty) a to pomoci `.map()`
6. Ostatni udaje o pacientovi vypisovat v `Home` komponente misto `UserDiagnoses`

2022-08-25 16:36 UTC, nazuzunana commented
Ahoj Nasti,

moc děkuju za všechny připomínky a rady. Sass rozhodně upravím podle
komentářů.
Co se týče zbytku změn, snažím se do komponenty UserDiagnoses poslat jen
diagnózy a přesunout veškeré info o pacientovi do komponenty Home. Nejsem
si jistá především Props v UserDiagnoses a key v Home. Pushla jsem
provedené změny i s errory, protože se mi nedaří pohnout z místa.

Srdečně,
Zuzana Červínová

čt 25. 8. 2022 v 10:33 odesílatel Anastasia Surikova <
***@***.***> napsal:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In react-ts/src/components/UserDiagnoses.tsx
> <https://github.com/mild-blue/tasks/pull/20#discussion_r954654653>:
>
> > +  // const [patient, setPatient] = useState<User>();
>
> +
>
> +  // useEffect(() => {
>
> +  //   setPatient(patientString ? JSON.parse(patientString) : undefined);
>
> +  // });
>
>
> vsak to tady skoro máš 😀 stačí jen vytahovat pacienta z localStorage
> vevnitr useEffect
>
> const [patient, setPatient] = useState<User>();
>
>
>
> useEffect(() => {
>
>    const patientString = localStorage.getItem(userLocalStorageKey);
>
>    setPatient(patientString ? JSON.parse(patientString) : undefined);
>
> });
>
>
> ------------------------------
>
> In react-ts/src/pages/Home.css
> <https://github.com/mild-blue/tasks/pull/20#discussion_r954655393>:
>
> > +.box .box__info {
>
> +  font-weight: 700;
>
> +}
>
>
> tohle by slo zanorit do .box
> ------------------------------
>
> In react-ts/src/pages/Home.scss
> <https://github.com/mild-blue/tasks/pull/20#discussion_r954655826>:
>
> > +
>
> +.diagnose__list {
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  gap: 1rem;
>
> +  max-width: 60rem;
>
> +}
>
> +
>
> +.box {
>
> +  @include flexCenter(row);
>
> +  justify-content: space-between;
>
> +  border: 0.06rem solid $border-color;
>
> +  width: 100%;
>
> +  padding: 1rem;
>
> +  gap: 1rem;
>
> +  .box__info {
>
>
> slo by pouzit &__info
> ------------------------------
>
> In react-ts/src/pages/Login.scss
> <https://github.com/mild-blue/tasks/pull/20#discussion_r954657201>:
>
> > ***@***.*** "../variables";
>
> ***@***.*** "../resets";
>
> +
>
> ***@***.*** flexCenter($direction) {
>
> +  display: flex;
>
> +  flex-direction: $direction;
>
> +  align-items: center;
>
> +}
>
> +
>
> ***@***.*** font() {
>
> +  font-size: $font-size;
>
> +  line-height: $line-height;
>
> +  letter-spacing: $letter-spacing;
>
> +}
>
> +
>
> +.login-container {
>
>
> mas toho vic s prefixem login-, ja bych to zanorila do jednoho tagu
>
> .login {
>
>   &-container {
>
>     ...
>
>   }
>
>
>
>   &-form {
>
>     ...
>
>   }
>
>
>
>   &-link {
>
>     ...
>
>   }
>
> }
>
>
> ------------------------------
>
> In react-ts/src/components/UserDiagnoses.tsx
> <https://github.com/mild-blue/tasks/pull/20#discussion_r954661214>:
>
> > +          <p className="box__info">{patient.diagnoses[0]}</p>
>
> +          <p className="box__info">{patient.diagnoses[1]}</p>
>
>
> pouzij patient.diagnoses.map()
> https://reactjs.org/docs/lists-and-keys.html#embedding-map-in-jsx
> ------------------------------
>
> In react-ts/src/pages/Home.tsx
> <https://github.com/mild-blue/tasks/pull/20#discussion_r954666670>:
>
> > @@ -10,8 +12,8 @@ export const Home = () => {
>
>     * 4. Send user's diagnoses to UserDiagnoses component
>
>     */
>
>    return (
>
> -    <div>
>
> -      <h1>Todo: Display name of the user here</h1>
>
> +    <div className="container home-container">
>
> +      <p className="user__name">Todo: Display name of the user here</p>
>
>
> Bylo by totiz hezke, kdybys pacienta vytahla z localStorage uz tady pomoci:
>
> const [patient, setPatient] = useState<User>();
>
>
>
> useEffect(() => {
>
>    const patientString = localStorage.getItem(userLocalStorageKey);
>
>    setPatient(patientString ? JSON.parse(patientString) : undefined);
>
> });
>
>
> a do <UserDiagnoses /> poslala jen ty diagnozy, ktere by se tam jen
> hloupe v .map() vypsali:
>
> <UserDiagnoses diagnoses={patient.diagnoses} />
>
>
> Coz znamena tedy upravy:
>
>    1. Vytahnout pacienta z LS v Home komponente a ulozit si ho do state
>    2. Osetrit pripad, kdy pacient neni ulozeny (jak se to deje ted v
>    UserDiagnoses) uz v Home komponente
>    3. Definovat Props komponenty UserDiagnoses, ktere by obsahovali jen
>    diagnozy
>    4. Poslat patient.diagnoses do UserDiagnoses
>    5. V UserDiagnoses vypisovat jen ty diagnozy (jak napovida nazev
>    komponenty) a to pomoci .map()
>    6. Ostatni udaje o pacientovi vypisovat v Home komponente misto
>    UserDiagnoses
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mild-blue/tasks/pull/20#pullrequestreview-1085000268>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4FZLUMWDJWOYL33IKBWLLV24VW3ANCNFSM56ZA6SUQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-29 14:22 UTC, misslecter requested changes

2022-08-29 14:22 UTC, misslecter commented on react-ts/src/components/UserDiagnoses.tsx
> +  diagnoses?: User;
`diagnoses: string[];`

2022-08-29 14:22 UTC, misslecter commented on react-ts/src/components/UserDiagnoses.tsx
> +        <li className="box__info">{diagnoses}</li>
```
{diagnoses.map(diagnosis => <li  key={diagnosis} className="box__info">{diagnosis}</li>}
```

2022-08-29 14:22 UTC, misslecter commented on react-ts/src/pages/Home.tsx
> +          ))}
a tady jen 
```
<UserDiagnoses  diagnoses={patient.diagnoses} />
```

2022-08-30 13:56 UTC, misslecter approved these changes

2022-09-05 12:39 UTC, closed without merging