Feature #3 modal window
mild-blue/tasks pull request #4
Opened 2021-12-25 17:42 UTC by NotLubo

2021-12-27 17:47 UTC, misslecter requested changes
Dobrá práce 👍

Pustil ses do celkem specifických Angular věcí, jako jsou `ViewContainerRef` a `ComponentRef`. A je super, že jsi prozkoumal, jak v Angular fungují servisy. Angular "filozofie" spíše propaguje to, abys místo rendrování komponent do kontejneru, používal přímo ty komponenty. Tedy místo `<div #modal></div>` by bylo "správněji" použít rovnou `<app-modal></app-modal>`, a odkazovat se na ní a její public metody.

Jen pro zajímavost, šlo by to vyřešit i bez použití servisy takto:

V app.component.html:
```
<button (click)="modalComponent.openModal()">Open modal</button>
<app-modal #modalComponent modalBody="Modal was successfully opened"></app-modal>
```

V modal.component.ts:
```
@Input() modalBody = '';

public open = false;

openModal(): void {
    this.open = true;
}

closeModal(): void {
    this.open = false;
}
```

V modal.component.html podmínit rendrování obsahu podle hodnoty `open`:
```
<div *ngIf="open" class="modal-window">
...
</div>
```

Ale je to jen jeden z možných způsobů, ten tvůj taky není špatný 😀

---

Zapracuj, prosím, komentáře, případně mi na ně odpověz. Budu se těšit :)

2021-12-27 17:47 UTC, misslecter commented on src/app/app.component.ts
> +  containerRef!: ViewContainerRef;
Je dobré se vyhnout použití `!`. Tímto říkáš, že tato proměnná nemůže být nikdy ani `null`, ani `undefined`, což není pravda. Kdybys náhodou zapomněl do šablony přidat kontejner, na který se odkazuješ, anebo udělal překlep v jeho id, pak je proměnná `containerRef` `undefined`. Díky `!` nikde dál v aplikaci `undefined` hodnotu ošetřuješ. Použij tady prosím `?` místo `!` (tímto naopak řekneš, že tato proměnná může být i `undefined`):

```
containerRef?: ViewContainerRef;
```

A dále ošetří `undefined` hodnotu této proměnné (viz další komentáře).

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.html
> +<div class="modal-window">
Jen osobní preference v pojmenování class, požívat parent classu co nejkratší, např. `class="modal"`, a u childů přidávat další částí, např.: `class="modal-content"`. Vyplatí se to pak u SCSS (viz další komentář).

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +    z-index: 60;
tady `z-index` už není potřeba, když parent element má `z-index: 50;`

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +  .modal-container {
Právě kdyby parent element měl `class="modal"`, tak u child elementu s `class="modal-container"` můžeš v SCSS použít `&`:

```
.modal {
    ...
    
    &-container {
        ....
    }
}
```

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +    padding: 2em;
Jen ze zvědavosti, proč používáš někde `em` a někde `px`?

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +
klidně bych přidala nějaký `padding`, který by to trochu odsadil od okrajů na menších obrazovkách.

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +      gap: 2.5rem;
Proč se tady používá `rem`, a ne `em`?

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +        font-family: Roboto-Bold, sans-serif;
Tohle by se mohlo nastavit pro celé `body` v globálních stylech. Nejspíš tu budeš chtít mít stejný font jako ve zbytku aplikace.

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +  all: unset;
good 👍

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +@media screen and (max-width: 600px) {
tohle se může psat rovnou v bloku `.modal-content`, tedy:

```
.modal-content {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 2.5rem;
      height: 100%;
      
      @media screen and (max-width: 600px) {
            flex-direction: column;
            gap: 1rem;
       }

      .modal-icon { ... }
      
      ...
}
```

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.ts
> +  @Output() closeModalEvent = new EventEmitter();
Posunout nad `constructor`

2021-12-27 17:47 UTC, misslecter commented on src/app/services/modal.service.ts
> +  private componentRef!: ComponentRef<ModalComponent>;
používat spíš `?` místo `!`

2021-12-27 17:47 UTC, misslecter commented on src/app/services/modal.service.ts
> +    this.componentRef.destroy();
Tady by právě mohl nastat problém kvůli `!`. Co když zavoláš `closeModal()` aniž bys přes tím volal `openModal()`? Proměnná `this.componentRef` by byla stálě ještě `undefined`, takže `closeModal()` hodí error. Správný postup by byl použít v definici a použití proměnné `?`:

```
private componentRef?: ComponentRef<ModalComponent>;
```

```
this.componentRef?.destroy();
```

2021-12-27 17:47 UTC, misslecter commented on src/styles.scss
> +  font-weight: bold;
Proč jsi místo lokálních fontů nepoužít import přímo z Google Fonts?

2021-12-27 17:47 UTC, misslecter commented on src/styles.scss
> +  font-family: Roboto-Bold;
Já mám ve zvyku lokální font-family mít v uvozovkách `font-family: 'Roboto Bold';`, a koukám, že MDN to má taky v uvozovkách https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +        gap: 1rem;
`gap` je super věc, musím ji taky začít používat 😀 👍

2021-12-27 17:47 UTC, misslecter commented on src/app/components/modal/modal.component.scss
> +  left: 0;
Tyto properties mohou být nahrazeny `inset: 0;`

2021-12-27 18:03 UTC, NotLubo commented on src/styles.scss
> +  font-weight: bold;
Celkovo sa snažím veci ako fonty, ikony, ... v projektoch vkladať lokálne. Príde mi to ako lepšia prax oproti vkladaniu hromady importov do headu. Ale je to len preferencia.

2021-12-27 18:04 UTC, NotLubo commented on src/styles.scss
> +  font-family: Roboto-Bold;
Ak je to jednoslovné tak to nie je potrebné ale ako prevenciu to môžem robiť.

2021-12-27 18:05 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +  left: 0;
Áno ďakujem :) Po roku v tailwinde mi už tieto veci začínajú unikať.

2021-12-27 18:08 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +    padding: 2em;
em je preklep štandartne všade používam rem. px používam len pri rozmeroch okna, čiže napr. aj v media

2021-12-27 18:17 UTC, NotLubo commented on src/app/app.component.ts
> +  @ViewChild('modal', { read: ViewContainerRef })
Opravené :)

2021-12-27 18:21 UTC, NotLubo commented on src/app/app.component.ts
> +  containerRef!: ViewContainerRef;
Zmenené a ošetrené.

2021-12-27 18:21 UTC, NotLubo commented on src/app/components/modal/modal.component.html
> +<div class="modal-window">
Výhody vidím ďakujem za tip :)

2021-12-27 18:23 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +    z-index: 60;
Nechal som sa ovládnuť z index paranojou :D Zmazané.

2021-12-27 18:28 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +  .modal-container {
Opravene

2021-12-27 18:29 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +@media screen and (max-width: 600px) {
Opravene

2021-12-27 18:29 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +      gap: 2.5rem;
viz hore

2021-12-27 18:34 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +        font-family: Roboto-Bold, sans-serif;
Súhlasím aj to tak štandartne samozrejme robím. Premiestnené.

2021-12-27 18:36 UTC, NotLubo commented on src/app/components/modal/modal.component.ts
> +  @Output() closeModalEvent = new EventEmitter();
Opravene

2021-12-27 18:38 UTC, NotLubo commented on src/app/services/modal.service.ts
> +  private componentRef!: ComponentRef<ModalComponent>;
Opravene

2021-12-27 18:40 UTC, NotLubo commented on src/app/services/modal.service.ts
> +    this.componentRef.destroy();
Opravené

2021-12-27 18:54 UTC, NotLubo commented on src/app/components/modal/modal.component.scss
> +
Pridal som okraje cez calc. Som na to viac zvyknutý a pri modálnych oknách tom viac verím. Ak máte ale samozrejme štandart nastavený na padding tak to prerobím.

2021-12-28 17:17 UTC, misslecter approved these changes

2022-01-06 16:57 UTC, merged